ad_interface: Fix for missing QObject include
This commit fixes the following error which cannot be identified when
using qmake because of its special precompiled headers:

```
/mnt/sda1/github.com/adtool/src/ad_interface.h:28:35: error: expected class-name before ‘{’ token
 class AdInterface: public QObject {
```